modLoader="javafml"
loaderVersion="[43,)"
license="AGPL-3.0"

[[mods]]
    modId="taloi"
    version="1.0.0"

    displayName="That's A Lot Of Items"
    authors="NewJumper"
    logoFile="logo_blue_white.png"
    description='''A mod that features a bunch of random content dumped into a block game.'''

[[dependencies.taloi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2, 1.20)"
    side="BOTH"

[[dependencies.taloi]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    side="BOTH"
