package com.newjumper.taloi.datagen.recipes;

import com.newjumper.taloi.ThatsALotOfItems;
import com.newjumper.taloi.block.ModBlocks;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.SingleItemRecipeBuilder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.crafting.conditions.IConditionBuilder;

import java.util.function.Consumer;

public class StonecuttingRecipesProvider extends RecipeProvider implements IConditionBuilder {
    public StonecuttingRecipesProvider(DataGenerator pGenerator) {
        super(pGenerator);
    }

    @Override
    protected void buildCraftingRecipes(Consumer<FinishedRecipe> consumer) {
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE.get()), ModBlocks.CHISELED_LIMESTONE_BRICKS.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_limestone_bricks_from_limestone_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE.get()), ModBlocks.LIMESTONE_SLAB.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_slab_from_limestone_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE.get()), ModBlocks.LIMESTONE_STAIRS.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_stairs_from_limestone_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE.get()), ModBlocks.LIMESTONE_WALL.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_wall_from_limestone_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.MARBLE.get()), ModBlocks.CHISELED_MARBLE.get(), 1).unlockedBy("has_material", has(ModBlocks.MARBLE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_marble_from_marble_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.MARBLE.get()), ModBlocks.MARBLE_SLAB.get(), 1).unlockedBy("has_material", has(ModBlocks.MARBLE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "marble_slab_from_marble_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.MARBLE.get()), ModBlocks.MARBLE_STAIRS.get(), 1).unlockedBy("has_material", has(ModBlocks.MARBLE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "marble_stairs_from_marble_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.MARBLE.get()), ModBlocks.MARBLE_WALL.get(), 1).unlockedBy("has_material", has(ModBlocks.MARBLE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "marble_wall_from_marble_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE.get()), ModBlocks.LIMESTONE_BRICKS.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_bricks_from_limestone_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE_BRICKS.get()), ModBlocks.CHISELED_LIMESTONE_BRICKS.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_limestone_bricks_from_limestone_bricks_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE_BRICKS.get()), ModBlocks.LIMESTONE_SLAB.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_brick_slab_from_limestone_bricks_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE_BRICKS.get()), ModBlocks.LIMESTONE_STAIRS.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_brick_stairs_from_limestone_bricks_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.LIMESTONE_BRICKS.get()), ModBlocks.LIMESTONE_WALL.get(), 1).unlockedBy("has_material", has(ModBlocks.LIMESTONE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "limestone_brick_wall_from_limestone_bricks_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE.get()), ModBlocks.CHISELED_SLATE.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_slate_from_slate_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE.get()), ModBlocks.SLATE_SLAB.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_slab_from_slate_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE.get()), ModBlocks.SLATE_STAIRS.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_stairs_from_slate_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE.get()), ModBlocks.SLATE_WALL.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_wall_from_slate_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE.get()), ModBlocks.SLATE_BRICKS.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_bricks_from_slate_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE_BRICKS.get()), ModBlocks.SLATE_BRICK_SLAB.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_brick_slab_from_slate_bricks_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE_BRICKS.get()), ModBlocks.SLATE_BRICK_STAIRS.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_brick_stairs_from_slate_bricks_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.SLATE_BRICKS.get()), ModBlocks.SLATE_BRICK_WALL.get(), 1).unlockedBy("has_material", has(ModBlocks.SLATE_BRICKS.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "slate_brick_wall_from_slate_bricks_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.ANDESITE), ModBlocks.CHISELED_ANDESITE.get(), 1).unlockedBy("has_material", has(Blocks.ANDESITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_andesite_from_andesite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_ANDESITE), ModBlocks.CHISELED_ANDESITE.get(), 1).unlockedBy("has_material", has(Blocks.POLISHED_ANDESITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_andesite_from_polished_andesite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.DIORITE), ModBlocks.CHISELED_DIORITE.get(), 1).unlockedBy("has_material", has(Blocks.DIORITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_diorite_from_diorite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_DIORITE), ModBlocks.CHISELED_DIORITE.get(), 1).unlockedBy("has_material", has(Blocks.POLISHED_DIORITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_diorite_from_polished_diorite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.DRIPSTONE_BLOCK), ModBlocks.CHISELED_DRIPSTONE_BLOCK.get(), 1).unlockedBy("has_material", has(Blocks.DRIPSTONE_BLOCK)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_dripstone_block_from_dripstone_block_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GRANITE), ModBlocks.CHISELED_GRANITE.get(), 1).unlockedBy("has_material", has(Blocks.GRANITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_granite_from_granite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.POLISHED_GRANITE), ModBlocks.CHISELED_GRANITE.get(), 1).unlockedBy("has_material", has(Blocks.POLISHED_GRANITE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_granite_from_polished_granite_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.TUFF), ModBlocks.POLISHED_TUFF.get(), 1).unlockedBy("has_material", has(Blocks.TUFF)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "polished_tuff_from_tuff_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.TUFF), ModBlocks.CHISELED_TUFF.get(), 1).unlockedBy("has_material", has(Blocks.TUFF)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_tuff_from_tuff_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(ModBlocks.POLISHED_TUFF.get()), ModBlocks.CHISELED_TUFF.get(), 1).unlockedBy("has_material", has(ModBlocks.POLISHED_TUFF.get())).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "chiseled_tuff_from_polished_tuff_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.NETHERRACK), ModBlocks.NETHERRACK_BRICKS.get(), 1).unlockedBy("has_material", has(Blocks.NETHERRACK)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "netherrack_bricks_from_netherrack_stonecutting"));

        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.WHITE_CONCRETE), ModBlocks.WHITE_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.WHITE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "white_concrete_slab_from_white_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.WHITE_CONCRETE), ModBlocks.WHITE_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.WHITE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "white_concrete_stairs_from_white_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.ORANGE_CONCRETE), ModBlocks.ORANGE_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.ORANGE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "orange_concrete_slab_from_orange_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.ORANGE_CONCRETE), ModBlocks.ORANGE_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.ORANGE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "orange_concrete_stairs_from_orange_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.MAGENTA_CONCRETE), ModBlocks.MAGENTA_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.MAGENTA_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "magenta_concrete_slab_from_magenta_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.MAGENTA_CONCRETE), ModBlocks.MAGENTA_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.MAGENTA_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "magenta_concrete_stairs_from_magenta_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIGHT_BLUE_CONCRETE), ModBlocks.LIGHT_BLUE_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.LIGHT_BLUE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "light_blue_concrete_slab_from_light_blue_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIGHT_BLUE_CONCRETE), ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.LIGHT_BLUE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "light_blue_concrete_stairs_from_light_blue_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.YELLOW_CONCRETE), ModBlocks.YELLOW_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.YELLOW_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "yellow_concrete_slab_from_yellow_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.YELLOW_CONCRETE), ModBlocks.YELLOW_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.YELLOW_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "yellow_concrete_stairs_from_yellow_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIME_CONCRETE), ModBlocks.LIME_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.LIME_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "lime_concrete_slab_from_lime_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIME_CONCRETE), ModBlocks.LIME_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.LIME_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "lime_concrete_stairs_from_lime_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.PINK_CONCRETE), ModBlocks.PINK_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.PINK_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "pink_concrete_slab_from_pink_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.PINK_CONCRETE), ModBlocks.PINK_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.PINK_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "pink_concrete_stairs_from_pink_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GRAY_CONCRETE), ModBlocks.GRAY_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.GRAY_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "gray_concrete_slab_from_gray_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GRAY_CONCRETE), ModBlocks.GRAY_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.GRAY_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "gray_concrete_stairs_from_gray_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIGHT_GRAY_CONCRETE), ModBlocks.LIGHT_GRAY_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.LIGHT_GRAY_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "light_gray_concrete_slab_from_light_gray_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.LIGHT_GRAY_CONCRETE), ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.LIGHT_GRAY_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "light_gray_concrete_stairs_from_light_gray_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.CYAN_CONCRETE), ModBlocks.CYAN_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.CYAN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "cyan_concrete_slab_from_cyan_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.CYAN_CONCRETE), ModBlocks.CYAN_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.CYAN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "cyan_concrete_stairs_from_cyan_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.PURPLE_CONCRETE), ModBlocks.PURPLE_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.PURPLE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "purple_concrete_slab_from_purple_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.PURPLE_CONCRETE), ModBlocks.PURPLE_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.PURPLE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "purple_concrete_stairs_from_purple_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BLUE_CONCRETE), ModBlocks.BLUE_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.BLUE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "blue_concrete_slab_from_blue_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BLUE_CONCRETE), ModBlocks.BLUE_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.BLUE_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "blue_concrete_stairs_from_blue_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BROWN_CONCRETE), ModBlocks.BROWN_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.BROWN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "brown_concrete_slab_from_brown_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BROWN_CONCRETE), ModBlocks.BROWN_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.BROWN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "brown_concrete_stairs_from_brown_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GREEN_CONCRETE), ModBlocks.GREEN_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.GREEN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "green_concrete_slab_from_green_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.GREEN_CONCRETE), ModBlocks.GREEN_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.GREEN_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "green_concrete_stairs_from_green_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.RED_CONCRETE), ModBlocks.RED_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.RED_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "red_concrete_slab_from_red_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.RED_CONCRETE), ModBlocks.RED_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.RED_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "red_concrete_stairs_from_red_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BLACK_CONCRETE), ModBlocks.BLACK_CONCRETE_SLAB.get(), 1).unlockedBy("has_material", has(Blocks.BLACK_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "black_concrete_slab_from_black_concrete_stonecutting"));
        SingleItemRecipeBuilder.stonecutting(Ingredient.of(Blocks.BLACK_CONCRETE), ModBlocks.BLACK_CONCRETE_STAIRS.get(), 1).unlockedBy("has_material", has(Blocks.BLACK_CONCRETE)).save(consumer, new ResourceLocation(ThatsALotOfItems.MOD_ID, "black_concrete_stairs_from_black_concrete_stonecutting"));
    }

    @Override
    public String getName() {
        return "Stonecutting Recipes";
    }
}
